# Generated by Django 3.2.9 on 2021-12-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('phone_number', models.CharField(default=None, max_length=200, null=True)),
                ('password', models.CharField(default=None, max_length=200, null=True)),
                ('school', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Massege_Student_FromManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=2500, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.manager')),
            ],
        ),
        migrations.CreateModel(
            name='MassegeT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=2500, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('phone_number', models.CharField(default=None, max_length=200, null=True)),
                ('password', models.CharField(default=None, max_length=200, null=True)),
                ('my_class', models.CharField(default=None, max_length=200, null=True)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.manager')),
                ('masseges', models.ManyToManyField(default=None, to='users.MassegeT')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('phone_number', models.CharField(default=None, max_length=200, null=True)),
                ('password', models.CharField(default=None, max_length=200, null=True)),
                ('present', models.IntegerField(default=0, null=True)),
                ('absent', models.IntegerField(default=0, null=True)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.manager')),
                ('massegeFromManager', models.ManyToManyField(default=None, to='users.Massege_Student_FromManager')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark_attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default=None, max_length=50, null=True)),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
