# Generated by Django 3.2.9 on 2021-12-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='read_homework',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='read',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
