# Generated by Django 3.2.9 on 2021-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
