# Generated by Django 3.2.9 on 2021-12-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massege_Student_FromTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=2500, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='massegeFromTeacher',
            field=models.ManyToManyField(default=None, to='users.Massege_Student_FromTeacher'),
        ),
    ]
