# Generated by Django 3.2.9 on 2021-12-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='green_percent',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='rad_percent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
