# Generated by Django 3.2.9 on 2021-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211222_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='read_massege',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
