# Generated by Django 3.2.9 on 2021-12-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211218_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massege_Student_FromManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=2500, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.manager')),
            ],
        ),
        migrations.DeleteModel(
            name='Massege_Student',
        ),
        migrations.AlterField(
            model_name='student',
            name='masseges',
            field=models.ManyToManyField(default=None, to='users.Massege_Student_FromManager'),
        ),
    ]
