# Generated by Django 3.2.9 on 2021-12-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date_ToDone',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
