# Generated by Django 3.2.9 on 2021-12-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211218_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='masseges',
            new_name='massegeFromManager',
        ),
    ]
