# Generated by Django 3.2.9 on 2021-12-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_homework_date_todone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='homework',
            field=models.ManyToManyField(default=None, to='users.Homework'),
        ),
    ]
