# Generated by Django 3.2.9 on 2021-12-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='masseget',
            name='read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='homework',
            field=models.ManyToManyField(default=None, to='users.Homework'),
        ),
    ]
