# Generated by Django 3.2.9 on 2021-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211222_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='homework',
            field=models.ManyToManyField(default=None, to='users.Homework'),
        ),
    ]
